version: '2.3'

services:

  neural-sum:
    build:
      context: ./
      args:
        upstream: 2.0.0-gpu-py3
    container_name: neural-sum
    tty: true
    stdin_open: true
    entrypoint: ipython3
    volumes:
      - type: bind
        source: ${SRC_DIR}
        target: /data/src
      - type: bind
        source: ${ARTIFACT_DIR}
        target: /artifacts
      - type: bind
        source: /home/tidal/Documents/neural-summarizer/milestone3/src
        target: /app
    runtime: nvidia
    # Env vars are read from .env file
    environment:
      - CUDA_VISIBLE_DEVICES=1
      - SRC_DIR=/data/src
      - ARTIFACTS_DIR=/artifacts
